/**
 * Created by Administrator on 2017/9/11 0011.
 */
var app=angular.module('yssc',['ionic','ionic-datepicker']);
//配置路由
app.config(function($stateProvider,$urlRouterProvider,$ionicConfigProvider){
    $ionicConfigProvider.tabs.position('botton');
    $stateProvider
        .state('ysMain',{
            url:'/Main',
            templateUrl:'tpl/main.html',
            controller:'MainCtrl'
        })
        .state('ysDetail',{
            url:'/Detail/:id',
            templateUrl:'tpl/detail.html',
            controller:'DetailCtrl'
        })
        .state('ysMainJia',{
            url:'/MainJia',
            templateUrl:'tpl/mainjia.html',
            parent:'ysMain',
            controller:'MainjiaCtrl'
        })
        .state('ysShopp',{
            url:'/Shopp',
            templateUrl:'tpl/shopp.html',
            parent:'ysMain',
            controller:'ShoppCtrl'
        })
        .state('ysMessage',{
            url:'/Message',
            templateUrl:'tpl/message.html',
            parent:'ysMain',
            controller:'MessageCtrl'
        })
        .state('ysEvaluate',{
            url:'/Evaluate',
            templateUrl:'tpl/evaluate.html',
            controller:'EvaluateCtrl'
        })
        .state('ysSearch',{
            url:'/Search',
            templateUrl:'tpl/search.html',
            controller:'SearchCtrl'
        })
        .state('ysClassify',{
            url:'/Classify',
            templateUrl:'tpl/classify.html',
            parent:'ysMain'
        })
        .state('ysInbox1',{
            url:'/Inbox1',
            templateUrl:'tpl/cla/inbox1.html',
            parent:'ysClassify'
        })
        .state('ysInbox2',{
            url:'/Inbox2',
            templateUrl:'tpl/cla/inbox2.html',
            parent:'ysClassify'
        })
        .state('ysInbox3',{
            url:'/Inbox3',
            templateUrl:'tpl/cla/inbox3.html',
            parent:'ysClassify'
        })
        .state('ysInbox4',{
            url:'/Inbox4',
            templateUrl:'tpl/cla/inbox4.html',
            parent:'ysClassify'
        })
        .state('ysInbox5',{
            url:'/Inbox5',
            templateUrl:'tpl/cla/inbox5.html',
            parent:'ysClassify'
        })
        .state('ysInbox6',{
            url:'/Inbox6',
            templateUrl:'tpl/cla/inbox6.html',
            parent:'ysClassify'
        }).state('ysInbox7',{
            url:'/Inbox7',
            templateUrl:'tpl/cla/inbox7.html',
            parent:'ysClassify'
        }).state('ysInbox8',{
            url:'/Inbox8',
            templateUrl:'tpl/cla/inbox8.html',
            parent:'ysClassify'
        })
        .state('ysEnter',{
            url:'/Enter/:name/:args',
            templateUrl:'tpl/myme/enter.html',
            controller:'EnterCtrl'
        })
        .state('ysRegister',{
            url:'/Register',
            templateUrl:'tpl/myme/register.html',
            controller:'RegisterCtrl'
        })
        .state('ysForget',{
            url:'/Forget',
            templateUrl:'tpl/myme/forget.html'

        })
        .state('ysResetPasswords',{
            url:'/ResetPasswords',
            templateUrl:'tpl/myme/ResetPasswords.html'
        })
        .state('ysAbout',{
            url:'/About',
            templateUrl:'tpl/about.html'
        })
        .state('ysPromotion',{
            url:'/Promotion',
            templateUrl:'tpl/promotion.html',
            controller:'PromotionCtrl'
        })
        .state('ysCoupon',{
            url:'/Coupon',
            templateUrl:'tpl/coupon.html'
        })
        .state('ysNewon',{
            url:'/Newon/:id',
            templateUrl:'tpl/newon.html',
            controller:'NewonCtrl'
        })
        .state('ysMyLogistics',{
            url:'/MyLogistics',
            templateUrl:'tpl/myme/myLogistics.html'
        })
        .state('ysMyCollect',{
            url:'/MyCollect',
            templateUrl:'tpl/myme/myCollect.html',
            controller:'MyCollectCtrl'
        })
        .state('ysMyPleis',{
            url:'/MyPleis',
            templateUrl:'tpl/myme/myPleis.html'
        })
        .state('ysEditAddress',{
            url:'/EditAddress',
            templateUrl:'tpl/editAddress.html'
        })
        .state('ysMyCoupon',{
            url:'/MyCoupon',
            templateUrl:'tpl/myme/myCoupon.html',
            controller:'MyCouponCtrl'
        })
        .state('ysMyIntegral',{
            url:'/MyIntegral',
            templateUrl:'tpl/myme/myIntegral.html',
            controller:'MyIntegralCtrl'
        })
        .state('ysMyLeave',{
            url:'/MyLeave',
            templateUrl:'tpl/myme/myLeave.html',
            controller:'MyLeaveCtrl'
        })
        .state('ysMyAbout',{
            url:'/MyAbout',
            templateUrl:'tpl/myme/myAbout.html'
        })
        .state('ysProfile',{
            url:'/Profile',
            templateUrl:'tpl/profile.html'
        })
        .state('ysMyShare',{
            url:'/MyShare',
            templateUrl:'tpl/myme/myShare.html'
        })
        .state('ysMyPresent',{
            url:'/MyPresent',
            templateUrl:'tpl/myme/mypresent.html',
            controller:'MyPresentCtrl'
        })
        .state('ysMyStored',{
            url:'/MyStored',
            templateUrl:'tpl/myme/mystored.html',
            controller:'MyStoredCtrl'
        })
        .state('ysMyMessaged',{
            url:'/MyMessaged',
            templateUrl:'tpl/myme/mymessaged.html',
            controller:'MyMessagedCtrl'
        })
        .state('ysMyMessageSet',{
            url:'/MyMessageSet',
            templateUrl:'tpl/myme/myMessageSet.html'
        })
        .state('ysMyPersonage',{
            url:'/MyPersonage',
            templateUrl:'tpl/myme/mypersonage.html',
            controller:'MyPersonageCtrl'
        })
        .state('ysMySecurity',{
            url:'/MySecurity',
            templateUrl:'tpl/myme/mysecurity.html',
            controller:'MySecurityCtrl'
        })
        .state('ysMyChangePassword',{
            url:'/MyChangePassword',
            templateUrl:'tpl/myme/myChangePassword.html',
            controller:'MyChangePasswordCtrl'
        })
        .state('ysMyAddress',{
            url:'/MyAddress',
            templateUrl:'tpl/myme/myAddress.html'
        })
        .state('ysMyModifyThePhone',{
            url:'/MyModifyThePhone',
            templateUrl:'tpl/myme/myModifyThePhone.html'
        })
        .state('ysMyChangCellPhoneNumber',{
            url:'/MyChangCellPhoneNumber',
            templateUrl:'tpl/myme/myChangCellPhoneNumber.html'
        })
        .state('ysMarket',{
            url:'/Market',
            templateUrl:'tpl/market.html'
        })
        .state('ysleave',{
            url:'/Leave',
            templateUrl:'tpl/leave.html',
            controller:'LeaveCtrl'
        })
        .state('ysOrder',{
            url:'/Order',
            templateUrl:'tpl/myme/order.html',
            controller:'OrderCtrl'
        })
        .state('ysRefund',{
            url:'/Refund',
            templateUrl:'tpl/myme/refund.html',
            controller:'RefundCtrl'
        })
        .state('ysConfirmation',{
            url:'/Confirmation/:cartDetail/:price',
            templateUrl:'tpl/confirmation.html',
            controller:'ConfirmationCtrl'
        })
        .state('ysPayment',{
            url:'/Payment',
            templateUrl:'tpl/payment.html'
        })
    ;
    $urlRouterProvider.otherwise('/Main');
});



